version : '3.5'

services:

  web:
    container_name: ${DOCKER_NAME}_web
    privileged: true
    ports:
      - 14080:80
    build:
      context: ../docker/web
      args:
        - DOCKER_WEB=${DOCKER_WEB}
        - DOCKER_DOCUMENT_PATH=${DOCKER_DOCUMENT_PATH}
    restart: always
    volumes:
      - type: bind
        source: /var/www/html
        target: /var/www

  db:
    container_name: ${DOCKER_NAME}_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    image: ${DOCKER_DB}
    ports:
      - ${DOCKER_DB_PORT}:3306
    volumes:
      - type: volume
        source: mysqldata
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_DB_ROOT_PAS}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

volumes:
  mysqldata:
